apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-website
spec:
  selector:
    matchLabels:
      app: react-website
  template:
    metadata:
      labels:
        app: react-website
    spec:
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.image.frontend_name }}:{{ default "latest" .Values.image.tag }}
          name: frontend
     
          ports:
            - containerPort: {{ .Values.image.frontend_port }}
              #name: reactport

        - image: {{ .Values.image.registry }}/{{ .Values.image.backend_name }}:{{ default "latest" .Values.image.tag }}
          name: backend
      
          ports:
            - containerPort: {{ .Values.image.backend_port }}
              #name: reactport
