apiVersion: v1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: react.{{ .Values.dns.name }}
      http:
        paths:
          - backend:
              serviceName: react-service
              servicePort: http
            path: /