apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: react.2df261e5fe9446d2b20d.eastus2.aksapp.io
      http:
        paths:
          - backend:
              serviceName: react-service
              servicePort: http
            path: /