apiVersion: v1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: react-website
      http:
        paths:
          - backend:
              serviceName: react-service
              servicePort: 3000
            path: /