name: Build and push the latest build to staging

on:
  push:
   

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          tags: ${{secrets.ACR_NAME}}/frontend:latest
          push: true
          
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          tags: ${{secrets.ACR_NAME}}/backend:latest
          push: true
